title = "Yu-Chieh Jesse Kuo"
baseURL = "http://ujkuo.github.io/"
theme = "researcher"
#disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = true           # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Yu-Chieh Kuo"
  description = "A simple personal website made by Hugo."
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  include_toc = true
  [params.footer]
    text = "By Yu-Chieh Jesse Kuo"
    url = "https://github.com/ujkuo"
    height = "50px"
    weight = "50px"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata" #Inconsolata
    fontSize = "20"
    pageWidth = "900px"
    avatarSize = "70px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fab fa-github-square"
    title = "Github"
    url = "https://github.com/ujkuo"
  [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/yu-chieh-kuo-94645b193/"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "ujkuo@ntu.im"
  [[params.socialIcons]]
    icon = "fab fa-facebook"
    title = "Facebook"
    url = "https://www.facebook.com/YuChieh.Jesse.Kuo"

[params.widgets]
  categories = true # Enable "Categories" widgets
  tage = true
  tags_counter = false # Enable counter


[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "CV"
    url = "/cv/cv.pdf"
    weight = 2
  [[menu.main]]
    name = "Courses"
    url = "/course/"
    weight = 3
  [[menu.main]]
    name = "Articles"
    url = "/posts/"
    weight = 4
  [[menu.main]]
    name = "Misc"
    url = "/misc"
    weight = 5

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
